# Generated by Django 4.2.10 on 2025-10-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("incidents", "0002_incident_management_enhancements"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="incidentcategory",
            name="unique_org_category_name",
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="incidents_i_categor_idx",
        ),
        migrations.RemoveIndex(
            model_name="incident",
            name="incidents_i_ai_gene_idx",
        ),
        migrations.AlterUniqueTogether(
            name="incidentcategory",
            unique_together={("organization", "name")},
        ),
    ]
