# Generated by Django 4.2.10 on 2025-10-29 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("threat_intelligence", "0002_auto_20251029_0717"),
    ]

    operations = []
