# Generated by Django 4.2.10 on 2025-10-28 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rtsp_url", models.URLField(blank=True, help_text="RTSP stream URL")),
                ("location", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "detection_interval",
                    models.IntegerField(
                        default=1, help_text="Seconds between detection runs"
                    ),
                ),
                ("confidence_threshold", models.FloatField(default=0.5)),
                ("last_detection_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Camera",
                "verbose_name_plural": "Cameras",
                "ordering": ["organization", "name"],
            },
        ),
        migrations.CreateModel(
            name="FaceIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_label", models.CharField(max_length=255)),
                (
                    "person_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Employee ID, department, etc.",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="face_identities/%Y/%m/%d/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("enrolled", "Enrolled"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="face_identities",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Identity",
                "verbose_name_plural": "Face Identities",
                "ordering": ["organization", "person_label"],
                "unique_together": {("organization", "person_label")},
            },
        ),
        migrations.CreateModel(
            name="FaceEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vector",
                    models.TextField(
                        help_text="Face embedding vector (temp: install pgvector)"
                    ),
                ),
                ("model_name", models.CharField(default="buffalo_l", max_length=50)),
                (
                    "source_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="face_embeddings/%Y/%m/%d/"
                    ),
                ),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="faces.faceidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["identity", "-created_at"],
                        name="faces_facee_identit_69c2f7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FaceDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frame_url", models.URLField(blank=True)),
                (
                    "frame_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="detections/%Y/%m/%d/"
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(help_text="Bounding box coordinates [x, y, w, h]"),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Detection confidence score"),
                ),
                (
                    "embedding_vector",
                    models.TextField(
                        blank=True, help_text="Face embedding vector (temp)", null=True
                    ),
                ),
                (
                    "similarity",
                    models.FloatField(
                        blank=True,
                        help_text="Cosine similarity with matched identity",
                        null=True,
                    ),
                ),
                ("is_match", models.BooleanField(default=False)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("landmarks", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="faces.camera",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="detections",
                        to="faces.faceidentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "Face Detection",
                "verbose_name_plural": "Face Detections",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="faces_faced_timesta_564440_idx"
                    ),
                    models.Index(
                        fields=["camera", "-timestamp"],
                        name="faces_faced_camera__7f91ea_idx",
                    ),
                    models.Index(
                        fields=["identity", "-timestamp"],
                        name="faces_faced_identit_303e6b_idx",
                    ),
                    models.Index(
                        fields=["is_match", "-timestamp"],
                        name="faces_faced_is_matc_179688_idx",
                    ),
                ],
            },
        ),
    ]
