# Generated by Django 4.2.10 on 2025-10-29 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0001_initial"),
        ("faces", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="access_point",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: link this camera to an access point",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cameras",
                to="access_control.accesspoint",
            ),
        ),
    ]
