# Generated by Django 4.2.10 on 2025-10-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visitor_assets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="ai_confidence",
            field=models.FloatField(
                blank=True, help_text="AI extraction confidence score", null=True
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="ai_extracted",
            field=models.BooleanField(
                default=False, help_text="Was info extracted by AI?"
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="ai_predicted_duration",
            field=models.IntegerField(
                blank=True, help_text="Predicted visit duration in minutes", null=True
            ),
        ),
        migrations.AddField(
            model_name="visitor",
            name="ai_suggested_access_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="visitor",
            name="extracted_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Raw AI extraction data"
            ),
        ),
    ]
